version: '3.8'

services:
  # Node.js application service
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]

  # MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
